### ISSUE TITLE
Dataset Used

### ISSUE THREAD

**Issue by ertza** [NagabhushanS/Machine-Learning-Based-Botnet-Detection#2]
Hi, I have some queries regarding the dataset you used. The pickled data is really weird and I'm unable to make any sense of it. e.g. these are the input features of the first example in the test dataset and I'm not really sure what are they?

`[7.44000000e-04 1.00000000e+00 2.07900000e+03 5.30000000e+01 2.46836957e+09 3.25324341e+09 2.00000000e+00 2.11000000e+02 2.19050700e+06]`

Can you please help identify that what actually are these 9 features? I thought they should be SrcIP, SrcPort etc but if they are those I don't know how you normalised them. Thanks in advance.

**Comment by ertza** [comment]
No worries, understood what they were after looking at the generate_dataset file. Thanks.

**Comment by aashna27** [comment]
@ertzaaafzal can you please tell what file are you referring to?
PLEASE help me with it, if you could tell the location or which one it is, it would be really helpful. 
Thanks a lot ☺️
