### ISSUE TITLE
Pickle data issue 

### ISSUE THREAD

**Issue by aashna27** [NagabhushanS/Machine-Learning-Based-Botnet-Detection#3]
I am unable to understand how pickle file was generated and also when i run it shows that p1 isn't an attribute of module.

p1 is in the flowdata.pickle file.

**Comment by aashna27** [comment]
![image](https://user-images.githubusercontent.com/26546120/48961041-aa3c9f80-ef97-11e8-896b-251e6ca61f9e.png)

Cant resolve this error . Someone please help!! 🙏

**Comment by thinszx** [comment]
well...maybe this isn't helpful to you anymore after about one year and a half...

I found this repo recently and found this 'pickle' file inside very strange. After looking into another 2 closed questions, I suppose that your question was answered in #2 but not quite clearly. The file 'ertzaaafal' called 'generate_dataset' could be the function written in '/src/dataset_load.py', which uses .binetflow files in CTU-13 datasets to generate .pickle files that can be easily read by python(but not people, sadly) and the .pickle file in path '~/datasets' is the file after processing(so you don't need to process it again)

Maybe you don't need this answer anymore but I still want to reply you to help others understand it. Sorry to disturb you with my poor English and hope my answer right and helpful :D.
